apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart-service-monitor
spec:
  namespaceSelector:
      matchNames:
      - robot-shop
  selector:
    matchLabels:
      service: cart
  endpoints:
  - port: http