kind: ServiceAccount
apiVersion: v1
metadata:
  name: cart-scaler-service-account
  namespace: robot-shop
---
apiVersion: v1
kind: Pod
metadata:
  name: cart-scaler
  namespace: robot-shop
spec:
  serviceAccount: cart-scaler-service-account
  containers:
    - name: kube-cart-scaler
      image: lachlanevenson/k8s-kubectl
      command:
        - /bin/sh
        - -ec
        - |
          # apk add --no-cache curl

          # kubectl apply -f /etc/config/petclinic-config.yaml

          i=0
          scaleup="1"
          while true; do
            if [[ $(( $i % 100 )) -eq "0" ]]; then
              if [[ $scaleup -eq "1" ]]; then
                r=$(( $RANDOM % 10 + 5 ))
                kubectl scale deployment cart --replicas $r
                echo "Scaled up"
                scaleup="0"
              else
                kubectl scale deployment cart --replicas 2
                echo "Scaled down"
                scaleup="1"
              fi
            fi

            #curl http://petclinic:28080/owners > /dev/null || true
            #curl http://petclinic:28080/ > /dev/null || true
            #curl http://petclinic:28080/vets > /dev/null|| true

            sleep 1
            i=$((i+1))
            echo "Incremented counter to $i"
          done
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: robot-shop
  name: deployments-updater
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "watch", "update", "patch", "create", "delete", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "create", "patch", "update", "delete", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: update-deployments
  namespace: robot-shop
subjects:
- kind: ServiceAccount
  name: cart-scaler-service-account
roleRef:
  kind: Role
  name: deployments-updater
  apiGroup: rbac.authorization.k8s.io